// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// turnbullem
Rcpp::List turnbullem(arma::vec x, arma::uvec censLow, arma::uvec censUpp, arma::uvec truncLow, arma::uvec truncUpp, bool cens, bool trunc, double tol, int maxiter);
RcppExport SEXP _longevity_turnbullem(SEXP xSEXP, SEXP censLowSEXP, SEXP censUppSEXP, SEXP truncLowSEXP, SEXP truncUppSEXP, SEXP censSEXP, SEXP truncSEXP, SEXP tolSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type censLow(censLowSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type censUpp(censUppSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type truncLow(truncLowSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type truncUpp(truncUppSEXP);
    Rcpp::traits::input_parameter< bool >::type cens(censSEXP);
    Rcpp::traits::input_parameter< bool >::type trunc(truncSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(turnbullem(x, censLow, censUpp, truncLow, truncUpp, cens, trunc, tol, maxiter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_longevity_turnbullem", (DL_FUNC) &_longevity_turnbullem, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_longevity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
