# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Turnbull's sets
#'
#' Given truncation and censoring sets,
#' construct disjoint increasing intervals whose
#' left and right endpoints lie in L and R
#' and which contain no other members of L and R
#'
#' @export
#' @keywords internal
.turnbull_intervals <- function(Lset, Rset) {
    .Call(`_longevity_turnbull_intervals`, Lset, Rset)
}

#' Identification sets
#'
#' @param tsets Turnbull's sets
#' @param lcens numeric vector of left censoring
#' @param rcens numeric vector of right censoring
#' @param ltrunc numeric vector of left truncation
#' @param rtrunc numeric vector of right truncation
#' @param trunc logical are observation truncated?
#' @export
#' @keywords internal
.censTruncLimits <- function(tsets, n, lcens, rcens, ltrunc, rtrunc, trunc) {
    .Call(`_longevity_censTruncLimits`, tsets, n, lcens, rcens, ltrunc, rtrunc, trunc)
}

#' Turnbull EM algorithm (low storage implementation)
#'
#' @param tsets Turnbull's sets
#' @param lcens numeric vector of left censoring
#' @param rcens numeric vector of right censoring
#' @param ltrunc numeric vector of left truncation
#' @param rtrunc numeric vector of right truncation
#' @param cens logical; if \code{FALSE}, then \code{censUpp = censLow} and a particular update can be avoided in the EM algorithm
#' @param tol tolerance level for terminating the EM algorithm
#' @param maxiter maximum number of iteration for the EM algorithm
#' @return a list with the probabilities and the standard errors
#' @keywords internal
.turnbull_em <- function(tsets, n, lcens, rcens, ltrunc, rtrunc, cens = TRUE, trunc = TRUE, tol = 1e-12, zerotol = 1e-40, maxiter = 1e5L) {
    .Call(`_longevity_turnbullem`, tsets, n, lcens, rcens, ltrunc, rtrunc, cens, trunc, tol, zerotol, maxiter)
}

