# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Turnbull EM algorithm (low storage implementation)
#'
#' @param x vector of ordered unique elements at which to estimate probabilities
#' @param truncLow integer vector in [0, J-1]; the lowest \code{x} such that \eqn{a_i < x} (left-truncation)
#' @param truncUpp integer vector in [0, J-1]; the largest \code{x} such that \eqn{b_i > x} (right-truncation)
#' @param censLow integer vector in [0, J-1]; the lowest \code{x} value at which the observation could be observed to fail (left censoring)
#' @param censUpp integer vector in [0, J-1]; the largest \code{x} value at which the observation could fail (right-censoring)
#' @param cens logical; if \code{FALSE}, then \code{censUpp = censLow} and a particular update can be avoided in the EM algorithm
#' @param tol tolerance level for terminating the EM algorithm
#' @param zerotol tolerance level for setting a probability to zero
#' @param maxiter maximum number of iteration for the EM algorithm
#' @return a list with the probabilities and the standard errors
#' @keywords internal
.turnbull_em <- function(x, censLow, censUpp, truncLow, truncUpp, cens = TRUE, trunc = TRUE, tol = 1e-12, maxiter = 1e5L) {
    .Call(`_longevity_turnbullem`, x, censLow, censUpp, truncLow, truncUpp, cens, trunc, tol, maxiter)
}

